version: "2"
linters:
  default: all
  disable:
    - varnamelen
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      default-case-required: true
    gocritic:
      enable-all: true
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    interfacebloat:
      max: 11
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '3'
        - '4'
        - '64'
        - '255'
        - '1024'
    nlreturn:
      block-size: 2
    prealloc:
      simple: false
      for-loops: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/ksf)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/ksf
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false