blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more 💬
  url: https://github.com/bytemare/ksf/discussions
  about: Do you need help? Did you make something with this project? Do you have an idea? Tell us about it!