name: Snyk

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '31 10 * * 0'

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@cdb760004ba9ea4d525f2e043745dfe85bb9077e
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
